### ISSUE TITLE
Sample project doesn't start up properly, lambda module issue

### ISSUE THREAD

**Issue by gadauto3** [terraformita/terraform-aws-serverless-app#4]
I've followed the instructions to get the project working and I'm unable to get it to work out of the box. However, it seems like just a minor tweak away from working.

First, here's what I see after I "terraform apply" and see the following at the aws_url:
<img width="1163" alt="Screenshot 2023-08-08 at 2 41 59 PM" src="https://github.com/terraformita/terraform-aws-serverless-app/assets/18454037/805d378f-b6c8-4179-b16a-c486f2fa7dbc">

Note that the version is blank and the site gets a 503 error.  I looked into this and see the following in CloudWatch which indicates the error is related to not finding the module 'serverless-http':
<img width="1072" alt="Screenshot 2023-08-08 at 2 42 43 PM" src="https://github.com/terraformita/terraform-aws-serverless-app/assets/18454037/35d42fe8-54b6-4fb2-8500-2bcab4f10f07">

Then I went into Lambda and found the following setup which is just the js source file:
<img width="791" alt="Screenshot 2023-08-08 at 2 43 29 PM" src="https://github.com/terraformita/terraform-aws-serverless-app/assets/18454037/ba300878-7366-40e1-918a-3c31ece85ef1">

It wasn't happening locally, so I tried uploading dependencies along with the index.js file.  This fixed the problem.
![Screenshot 2023-08-08 at 2 54 07 PM](https://github.com/terraformita/terraform-aws-serverless-app/assets/18454037/d4e4865c-1888-41c9-8ac2-fcf041a1b890)

So then I went back to the tf files and I see that the modules/dependencies are captured in the layer block (compatible_runtimes = [var.backend.modules[0].runtime]"), but I'm not clear why that's not making it into the lambda.  Is this issue just with me or everyone?

**Comment by gadauto3** [comment]
Ok, more progress, in reading the [creation spec on Lambda layers](https://docs.aws.amazon.com/lambda/latest/dg/packaging-layers.html) (and maybe this has changed since the project was built), the node-modules/ directory should be in a folder called `nodejs`.  I uploaded a layer where the zip folder structure went from layer/node-modules to nodejs/node-modules and the app works fine.

**Comment by kurianoff** [comment]
Hey @gadauto3 , yes - I mentioned this in the article on Medium: it's a specifics of AWS Lambda functions - if you have a nodejs application, all content of the lambda layer should be placed under the `nodejs` directory, otherwise the layer won't work, and Lambda function will be unable to locate any node modules.

Great that you've sorted it out! I'm really Happy to see the solution working for you.

**Comment by gadauto3** [comment]
Thanks @kurianoff , I actually found this repository independently of the [Medium article](https://medium.com/@kurianoff/deploy-serverless-react-app-with-node-js-express-backend-to-aws-with-terraform-in-under-15-minutes-2386bf0c58e9) which definitely pointed me to the right issue: by default, npm installs to the working directory (backend in this case), so I had to manually move my node_modules and package* files into nodejs.  Everything's working fine, thanks.
